### ISSUE TITLE
Astro::Montenbruck::Ephemeris mentions non-existent time function t2dt

### ISSUE THREAD

**Issue by tbrowder** [skrushinsky/astro-montenbruck#13]
The user is recommended to use Ephemeral time and is told to use the t2dt function to convert UT to ET, but I can find no such function documented in the Time.pm module.

**Comment by skrushinsky** [comment]
It's great that you noticed it!  The function is called `delta_t`, and the module is `Astro::Montenbruck::Time::DeltaT`. Now the documentation is up to date.
