### ISSUE TITLE
Script phases.pl puts an asterisk after an entry but does not explain it for UTC year 2021

### ISSUE THREAD

**Issue by tbrowder** [skrushinsky/astro-montenbruck#14]

**Comment by skrushinsky** [comment]
Oh, it's a kind of cursor, showing current lunar phase. For instance:

``` 
Date          :  2021-02-22
 
First Quarter :  2021-02-19 21:48:11 *
Full Moon     :  2021-02-27 11:20:33
```

The query date, **Feb 22**,  belongs to the First Quarter, while the next phase will start on **Feb 27**. I've just added the explanation to the pod text.
