### ISSUE TITLE
Function 'jd2cal' optional named argument 'gregorian' should be named 'julian'

### ISSUE THREAD

**Issue by tbrowder** [skrushinsky/astro-montenbruck#20]
For this user, the name of the argument is counter-intuitive. At first glance it seems that the default value should be true, and the user should enter a false value if an old-style value is desired.

Another option could be to have the same optional named argument as the cal2jd function, 'gregorian_start'.

(Note this issue is being filed by a former Perl user who now speaks Raku more fluently and is trying to port the functions to Raku. This user also is a very new user of astronomical calculations, so please forgive me if this issue isn't apprpriate.)

**Comment by skrushinsky** [comment]
> At first glance it seems that the default value should be true, and the user should enter a false value if an old-style value is desired.

Exactly, the default value is 1 (*true*). This is done by the following line of code: 

```
my %arg = ( gregorian => 1, @_ );
``` 
The option `gregorian => 0` could be helpful only in rare, non-trivial cases. Normally, we don't need it at all.

At the other hand, **cal2jd** has `gregorian_start` option for another reason. Not all countries adopted Gregorian calendar in 1582 (Russia, for instance, did that in the 20-th century). Sometimes, when we are working with historical dates it is necessary to provide exact date when Gregorian calendar came into effect. 

Again, in most cases the option may be omitted. Usually, we deal with artificial *proleptic Gregorian calendar*, which ignores historical circumstances.

**Comment by tbrowder** [comment]
Thanks.
