### ISSUE TITLE
Code request

### ISSUE THREAD

**Issue by souabi** [skrushinsky/astro-montenbruck#3]
@skrushinsky Dear Sergey,

We are looking for a developer with knowledge astrology like you demonstrate in your project. If you are in for a project (participation in a dutch startup!) please respond on this comment so we can have a chat.

Kind regards,
Souabi

**Comment by skrushinsky** [comment]
Hi, Souabi!
Thank you, sounds interesting. Looking forward to find out more.

Best regards,
Sergey

**Comment by souabi** [comment]
Hi Sergey,

Awesome. I will talk to the other guys tomorrow. I will contact you with more information and perhaps we can setup an online session.

Kind regards,
Souabi
