### ISSUE TITLE
Version 1.03 has errors building via a downloaded zip file

### ISSUE THREAD

**Issue by tbrowder** [skrushinsky/astro-montenbruck#5]
Following instructions:

    $ perl Build.PL
    WARNING: the following files are missing in your kit:
                       Meta.json
                       Metalyml
    Please inform the author.
    ...

 In spite of the warnings I tried:

    $ ./Build
    Warning: Build.PL has been altered.  You may need to run 'perl Build.PL' again.
    Building Astro::Montenbruck

Then I tried to run riseset_year.pl and seemed to get reasonable data but got warnings about 
"useless use of division..." and other errors.

**Comment by skrushinsky** [comment]
Fixed in the latest version
