### ISSUE TITLE
Feature request: all scripts need an option for NO text coloring

### ISSUE THREAD

**Issue by tbrowder** [skrushinsky/astro-montenbruck#6]

**Comment by tbrowder** [comment]
Oh, I think the mostly undocumented "print_data" option does that. I'll check it out.

**Comment by skrushinsky** [comment]
I replaced color schemes with more flexible `Astro::Montenbruck::Utils::Theme` classes. To avoid text coloring, you may use now
`--theme=colorless` command option or simply add `--no-colors` flag, e.g.: `perl ./scipt/phases.pl --no-colors`.

**Comment by tbrowder** [comment]
On Sun, Jan 10, 2021 at 06:29 Sergey Krushinsky <notifications@github.com>
wrote:

Thanks!
